name: Build, Test and Publish

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on : ubuntu-latest
    steps :
      - name: Checkout
          uses: actions/checkout@v2
      - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username : ${{ secrets.DOCKER_HUB_USER }}
          password : ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name : Build and push
        uses : docker/build-push-action@v2
        with :
          context: .
          file : ./frontend/Dockerfile
          push : true
          tags : frontegg/opensaas:latest
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm run build
      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
